version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: li881207
      MYSQL_DATABASE: wow_database
      MYSQL_USER: nfeng
      MYSQL_PASSWORD: li881207
  web:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               rake db:migrate &&
               rake db:seed &&
               rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://nfeng:li881207@db/wow_database
